---

- name: Ensure 'sudo' group exists
  group:
    name: sudo
    state: present

- name: Add root
  import_tasks: users/root.yml


- name: Add thies
  import_tasks: users/thies.yml

- name: Add cedi
  import_tasks: users/cedi.yml


