---

- name: Update apt-get repo and cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: safe

- name: Install basic packages
  debug:
    msg: "{{ base_system_packages }}"

- name: Install basic packages
  apt:
    name: "{{ base_system_packages }}"
    state: present

- name: Install pip packages
  debug:
    msg: "{{ base_pip_packages }}"

- name: Install pip packages
  become: true
  pip:
    name: "{{ base_pip_packages }}"
    executable: pip3

- name: Install python2 pip packages
  debug:
    msg: "{{ base_pip_packages }}"

- name: Install python2 pip packages
  become: true
  pip:
    name: "{{ base_pip2_packages }}"
    executable: pip

- name: Install cargo packages
  debug:
    msg: "{{ base_cargo_packages }}"

- name: Install cargo packages
  become: true
  shell:
    cmd: cargo install "{{ item }}" --root /usr/local/bin/
  loop: "{{ base_cargo_packages }}"

- name: Install snap packages
  debug:
    msg: "{{ base_snap_packages }}"

- name: Install snap packages
  become: true
  snap:
    name: "{{ base_snap_packages }}"
    state: present
