---

- name: Update apt-get repo and cache
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
    upgrade: safe

- name: Install basic packages
  debug:
    msg: "{{ base__system_packages }}"

- name: Install basic packages
  apt:
    name: "{{ base__system_packages }}"
    state: present
