---

- name: Check os compatability with this role
  assert:
    that: "ansible_os_family|lower == 'debian'"
    msg: "{{ ansible_os_family }} is probably not supported by this role"

- name: Install dependencies required by this role
  import_tasks: install.yml
  become: true

- name: Add ansible user
  import_tasks: adduser.yml
  become: true


