---

- name: Check os compatability with this role
  assert:
    that: "ansible_os_family|lower in base__supported_os_families"
    msg: "{{ ansible_os_family }} is probably not supported by this role"

- name: Include os specific variables
  include_vars: "{{ ansible_os_family|lower }}.yml"

- name: Install dependencies required by this role
  import_tasks: install.yml
  become: true

- name: Add ansible user
  import_tasks: adduser.yml
  become: true


